import { createRoot } from "react-dom/client";
import { JournalEntry } from "@workspace/api-client-react";
import { JournalCalendar } from "./JournalCalendar";
import html2canvas from "html2canvas";

export async function exportCalendarImage(journals: JournalEntry[], month: Date, workspaceName: string) {
  // Create a container off-screen
  const container = document.createElement("div");
  container.style.position = "absolute";
  container.style.left = "-9999px";
  container.style.top = "-9999px";
  // The user wants a 2000x2000 image. We make the base 1000x1000 and scale by 2.
  container.style.width = "1000px";
  container.style.height = "1000px";
  container.style.backgroundColor = "#020817"; // matching the dark background
  document.body.appendChild(container);

  const root = createRoot(container);
  
  // Render the component
  root.render(
    <div style={{ width: "1000px", height: "1000px", padding: "40px" }} className="bg-[#020817] d-flex flex-column">
      <div className="text-center mb-4">
        <h2 className="text-light fw-bold m-0" style={{ fontSize: "2rem" }}>{workspaceName} Trading Journal</h2>
      </div>
      
      <div className="flex-grow-1" style={{ display: 'flex', flexDirection: 'column' }}>
        <JournalCalendar 
          journals={journals} 
          selectedDate={null} 
          onSelectDate={() => {}} 
          initialMonth={month} 
          isExport={true} 
          workspaceName={workspaceName}
        />
      </div>
      
      <div className="mt-auto text-center text-secondary fw-medium pt-4" style={{ borderTop: "1px solid #1e293b", opacity: 0.8, fontSize: "1.1rem" }}>
        Generated by Piplabs x GraceFXC
      </div>
    </div>
  );

  // Wait for it to mount and render fully
  await new Promise(resolve => setTimeout(resolve, 300));

  try {
    const canvas = await html2canvas(container.firstChild as HTMLElement, {
      backgroundColor: "#020817",
      scale: 2, // 1000x1000 * 2 = 2000x2000
      useCORS: true,
      logging: false,
    });

    const url = canvas.toDataURL("image/png");
    const link = document.createElement("a");
    link.href = url;
    link.download = `Calendar_Stats_${month.getFullYear()}_${month.getMonth() + 1}.png`;
    link.click();
  } catch (error) {
    console.error("Failed to generate calendar image", error);
  } finally {
    root.unmount();
    document.body.removeChild(container);
  }
}
